import type { ImageRow } from './types';

const now = (daysOffset: number): string =>
  new Date(Date.now() - daysOffset * 86_400_000).toISOString();

const TEST_URL = (n: number) => `http://localhost:3001/test-images/img-${n}.webp`;
const TEST_KEY = (n: number) => `test-images/img-${n}.webp`;

export const MOCK_IMAGES: ImageRow[] = [
  {
    id: 'img-001',
    s3_key: TEST_KEY(1),
    s3_url: TEST_URL(1),
    original_prompt: 'a cat sitting on a windowsill',
    enhanced_prompt: 'a fluffy cat sitting on a sunny windowsill',
    tags: ['cat', 'animal', 'indoor', 'cozy'],
    style: 'Photorealistic',
    subject: 'Cat on windowsill',
    mood: 'Calm',
    color_palette: ['#FFD700', '#8B4513'],
    use_case: 'Wallpaper',
    filename: 'cat-windowsill.webp',
    created_at: now(30),
  },
  {
    id: 'img-002',
    s3_key: TEST_KEY(2),
    s3_url: TEST_URL(2),
    original_prompt: 'dogs running in a park',
    enhanced_prompt: 'happy dogs running through a green park',
    tags: ['dog', 'animal', 'outdoor', 'park'],
    style: 'Photorealistic',
    subject: 'Dogs in park',
    mood: 'Vibrant',
    color_palette: ['#228B22', '#8B4513'],
    use_case: 'Banner',
    filename: 'dogs-park.webp',
    created_at: now(29),
  },
  {
    id: 'img-003',
    s3_key: 'mock/futuristic-city.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'a futuristic city at night',
    enhanced_prompt: 'a glowing futuristic city skyline at night with neon lights',
    tags: ['city', 'night', 'futuristic', 'neon'],
    style: '3D Render',
    subject: 'Futuristic city',
    mood: 'Futuristic',
    color_palette: ['#7C5CFF', '#000000'],
    use_case: 'Social Media',
    filename: 'futuristic-city.webp',
    created_at: now(28),
  },
  {
    id: 'img-004',
    s3_key: 'mock/mountain-sunset.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'a mountain landscape at sunset',
    enhanced_prompt: 'a breathtaking mountain landscape with golden sunset',
    tags: ['mountain', 'landscape', 'sunset', 'nature'],
    style: 'Photorealistic',
    subject: 'Mountain sunset',
    mood: 'Calm',
    color_palette: ['#FF8C00', '#4169E1'],
    use_case: 'Wallpaper',
    filename: 'mountain-sunset.webp',
    created_at: now(27),
  },
  {
    id: 'img-005',
    s3_key: 'mock/robot-flower.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'robot holding a flower',
    enhanced_prompt: 'a gentle robot holding a delicate flower in its metal hands',
    tags: ['robot', 'flower', 'scifi', 'contrast'],
    style: '3D Render',
    subject: 'Robot with flower',
    mood: 'Minimalist',
    color_palette: ['#C0C0C0', '#FF69B4'],
    use_case: 'Editorial',
    filename: 'robot-flower.webp',
    created_at: now(26),
  },
  {
    id: 'img-006',
    s3_key: 'mock/cats-dogs.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'cats and dogs together',
    enhanced_prompt: 'cats and dogs playing together in a garden',
    tags: ['cat', 'dog', 'animal', 'garden'],
    style: 'Oil Painting',
    subject: 'Cats and dogs together',
    mood: 'Vibrant',
    color_palette: ['#228B22', '#FFD700'],
    use_case: 'Social Media',
    filename: 'cats-dogs.webp',
    created_at: now(25),
  },
  {
    id: 'img-007',
    s3_key: 'mock/dark-forest.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'dark forest with fog',
    enhanced_prompt: 'a mysterious dark forest shrouded in thick fog',
    tags: ['forest', 'dark', 'fog', 'mystery'],
    style: 'Oil Painting',
    subject: 'Dark forest',
    mood: 'Dark',
    color_palette: ['#2F4F4F', '#000000'],
    use_case: 'Wallpaper',
    filename: 'dark-forest.webp',
    created_at: now(24),
  },
  {
    id: 'img-008',
    s3_key: 'mock/abstract-art.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'abstract colorful painting',
    enhanced_prompt: 'a vibrant abstract painting with bold colors and shapes',
    tags: ['abstract', 'colorful', 'art', 'modern'],
    style: 'Oil Painting',
    subject: 'Abstract art',
    mood: 'Vibrant',
    color_palette: ['#FF1493', '#00CED1'],
    use_case: 'Banner',
    filename: 'abstract-art.webp',
    created_at: now(23),
  },
  {
    id: 'img-009',
    s3_key: 'mock/cyberpunk-cat.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'a cat in a cyberpunk alley',
    enhanced_prompt: 'a cyberpunk alley illuminated by neon signs with a cat',
    tags: ['cat', 'cyberpunk', 'neon', 'night'],
    style: '3D Render',
    subject: 'Cyberpunk cat',
    mood: 'Futuristic',
    color_palette: ['#7C5CFF', '#FF1493'],
    use_case: 'Social Media',
    filename: 'cyberpunk-cat.webp',
    created_at: now(22),
  },
  {
    id: 'img-010',
    s3_key: 'mock/minimalist-room.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'minimalist white room',
    enhanced_prompt: 'a clean minimalist white room with soft natural light',
    tags: ['minimalist', 'interior', 'white', 'clean'],
    style: 'Photorealistic',
    subject: 'Minimalist room',
    mood: 'Minimalist',
    color_palette: ['#FFFFFF', '#F5F5F5'],
    use_case: 'Editorial',
    filename: 'minimalist-room.webp',
    created_at: now(21),
  },
  {
    id: 'img-011',
    s3_key: 'mock/mars-rover.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'robot exploring mars',
    enhanced_prompt: 'a robotic rover exploring the red surface of mars',
    tags: ['robot', 'mars', 'scifi', 'space'],
    style: '3D Render',
    subject: 'Mars rover',
    mood: 'Futuristic',
    color_palette: ['#B22222', '#FFD700'],
    use_case: 'Banner',
    filename: 'mars-rover.webp',
    created_at: now(20),
  },
  {
    id: 'img-012',
    s3_key: 'mock/dogs-fire.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'dogs sleeping by the fire',
    enhanced_prompt: 'two dogs sleeping peacefully by a warm fireplace',
    tags: ['dog', 'cozy', 'fire', 'indoor'],
    style: 'Oil Painting',
    subject: 'Dogs by the fire',
    mood: 'Calm',
    color_palette: ['#FF4500', '#8B4513'],
    use_case: 'Wallpaper',
    filename: 'dogs-fire.webp',
    created_at: now(19),
  },
  {
    id: 'img-013',
    s3_key: 'mock/neon-cat.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'a cat in the rain at night',
    enhanced_prompt: 'a cat walking through neon-lit rainy streets at night',
    tags: ['cat', 'rain', 'night', 'neon', 'urban'],
    style: '3D Render',
    subject: 'Neon cat in rain',
    mood: 'Futuristic',
    color_palette: ['#7C5CFF', '#FF1493'],
    use_case: 'Social Media',
    filename: 'neon-cat.webp',
    created_at: now(18),
  },
  {
    id: 'img-014',
    s3_key: 'mock/ocean-wave.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'a giant ocean wave at sunset',
    enhanced_prompt: 'a dramatic ocean wave crashing under a golden sunset',
    tags: ['ocean', 'wave', 'sunset', 'nature'],
    style: 'Photorealistic',
    subject: 'Ocean wave',
    mood: 'Dramatic',
    color_palette: ['#FF8C00', '#006994'],
    use_case: 'Wallpaper',
    filename: 'ocean-wave.webp',
    created_at: now(17),
  },
  {
    id: 'img-015',
    s3_key: 'mock/vintage-cafe.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'a vintage cafe interior',
    enhanced_prompt: 'a cozy vintage cafe with warm lighting and old books',
    tags: ['cafe', 'vintage', 'cozy', 'indoor', 'warm'],
    style: 'Oil Painting',
    subject: 'Vintage cafe',
    mood: 'Calm',
    color_palette: ['#8B4513', '#FFD700'],
    use_case: 'Editorial',
    filename: 'vintage-cafe.webp',
    created_at: now(16),
  },
  {
    id: 'img-016',
    s3_key: 'mock/space-station.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'a space station orbiting earth',
    enhanced_prompt: 'a detailed space station orbiting high above the blue earth',
    tags: ['space', 'station', 'scifi', 'earth', 'future'],
    style: '3D Render',
    subject: 'Space station',
    mood: 'Futuristic',
    color_palette: ['#006994', '#C0C0C0'],
    use_case: 'Banner',
    filename: 'space-station.webp',
    created_at: now(15),
  },
  {
    id: 'img-017',
    s3_key: 'mock/cherry-blossoms.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'cherry blossoms in spring',
    enhanced_prompt: 'delicate cherry blossom petals floating in spring breeze',
    tags: ['cherry', 'blossoms', 'spring', 'nature', 'pink'],
    style: 'Photorealistic',
    subject: 'Cherry blossoms',
    mood: 'Calm',
    color_palette: ['#FFB7C5', '#228B22'],
    use_case: 'Wallpaper',
    filename: 'cherry-blossoms.webp',
    created_at: now(14),
  },
  {
    id: 'img-018',
    s3_key: 'mock/robot-dj.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'robot dj at a concert',
    enhanced_prompt: 'a robot dj performing on stage with laser lights',
    tags: ['robot', 'dj', 'concert', 'music', 'neon'],
    style: '3D Render',
    subject: 'Robot DJ',
    mood: 'Vibrant',
    color_palette: ['#FF1493', '#7C5CFF'],
    use_case: 'Social Media',
    filename: 'robot-dj.webp',
    created_at: now(13),
  },
  {
    id: 'img-019',
    s3_key: 'mock/autumn-path.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'an autumn path through the woods',
    enhanced_prompt: 'a winding path covered in golden autumn leaves',
    tags: ['autumn', 'path', 'woods', 'nature', 'golden'],
    style: 'Photorealistic',
    subject: 'Autumn path',
    mood: 'Calm',
    color_palette: ['#FFD700', '#FF8C00'],
    use_case: 'Wallpaper',
    filename: 'autumn-path.webp',
    created_at: now(12),
  },
  {
    id: 'img-020',
    s3_key: 'mock/dark-city.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'a dark gothic city skyline',
    enhanced_prompt: 'a gothic city with towering spires under a full moon',
    tags: ['city', 'gothic', 'dark', 'moon', 'architecture'],
    style: '3D Render',
    subject: 'Gothic city',
    mood: 'Dark',
    color_palette: ['#2F4F4F', '#C0C0C0'],
    use_case: 'Social Media',
    filename: 'dark-city.webp',
    created_at: now(11),
  },
  {
    id: 'img-021',
    s3_key: 'mock/tropical-beach.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'a tropical beach at dawn',
    enhanced_prompt: 'a serene tropical beach with palm trees at dawn',
    tags: ['beach', 'tropical', 'palm', 'dawn', 'ocean'],
    style: 'Photorealistic',
    subject: 'Tropical beach',
    mood: 'Calm',
    color_palette: ['#00CED1', '#FFD700'],
    use_case: 'Wallpaper',
    filename: 'tropical-beach.webp',
    created_at: now(10),
  },
  {
    id: 'img-022',
    s3_key: 'mock/cat-space.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'a cat floating in space',
    enhanced_prompt: 'a cute cat astronaut floating in outer space',
    tags: ['cat', 'space', 'astronaut', 'scifi', 'cute'],
    style: '3D Render',
    subject: 'Cat astronaut',
    mood: 'Playful',
    color_palette: ['#000000', '#FFD700'],
    use_case: 'Social Media',
    filename: 'cat-space.webp',
    created_at: now(9),
  },
  {
    id: 'img-023',
    s3_key: 'mock/flower-field.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'a field of wildflowers',
    enhanced_prompt: 'a vast field of colorful wildflowers under blue sky',
    tags: ['flowers', 'field', 'nature', 'colorful', 'spring'],
    style: 'Photorealistic',
    subject: 'Wildflower field',
    mood: 'Vibrant',
    color_palette: ['#FFD700', '#FF1493'],
    use_case: 'Banner',
    filename: 'flower-field.webp',
    created_at: now(8),
  },
  {
    id: 'img-024',
    s3_key: 'mock/samurai-robot.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'a robot samurai in a bamboo forest',
    enhanced_prompt: 'a sleek robot samurai standing in a misty bamboo forest',
    tags: ['robot', 'samurai', 'bamboo', 'scifi', 'warrior'],
    style: '3D Render',
    subject: 'Robot samurai',
    mood: 'Dramatic',
    color_palette: ['#228B22', '#C0C0C0'],
    use_case: 'Editorial',
    filename: 'samurai-robot.webp',
    created_at: now(7),
  },
  {
    id: 'img-025',
    s3_key: 'mock/starry-night.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'a starry night over a lake',
    enhanced_prompt: 'a starry night sky reflected on a calm mountain lake',
    tags: ['night', 'stars', 'lake', 'nature', 'reflection'],
    style: 'Photorealistic',
    subject: 'Starry night lake',
    mood: 'Calm',
    color_palette: ['#000041', '#FFD700'],
    use_case: 'Wallpaper',
    filename: 'starry-night.webp',
    created_at: now(6),
  },
  {
    id: 'img-026',
    s3_key: 'mock/cyberpunk-street.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'a cyberpunk street market',
    enhanced_prompt: 'a bustling cyberpunk street market with holographic signs',
    tags: ['cyberpunk', 'market', 'neon', 'urban', 'night'],
    style: '3D Render',
    subject: 'Cyberpunk market',
    mood: 'Futuristic',
    color_palette: ['#7C5CFF', '#FF1493'],
    use_case: 'Social Media',
    filename: 'cyberpunk-street.webp',
    created_at: now(5),
  },
  {
    id: 'img-027',
    s3_key: 'mock/dog-beach.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'a dog playing at the beach',
    enhanced_prompt: 'a golden retriever playing in ocean waves at sunset',
    tags: ['dog', 'beach', 'ocean', 'sunset', 'playful'],
    style: 'Photorealistic',
    subject: 'Dog at beach',
    mood: 'Vibrant',
    color_palette: ['#FFD700', '#006994'],
    use_case: 'Banner',
    filename: 'dog-beach.webp',
    created_at: now(4),
  },
  {
    id: 'img-028',
    s3_key: 'mock/abstract-geometric.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'geometric abstract pattern',
    enhanced_prompt: 'a mesmerizing geometric pattern with bold contrasting colors',
    tags: ['abstract', 'geometric', 'pattern', 'modern', 'colorful'],
    style: 'Oil Painting',
    subject: 'Geometric pattern',
    mood: 'Vibrant',
    color_palette: ['#FF1493', '#00CED1'],
    use_case: 'Banner',
    filename: 'abstract-geometric.webp',
    created_at: now(3),
  },
  {
    id: 'img-029',
    s3_key: 'mock/robot-garden.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'a robot tending a garden',
    enhanced_prompt: 'a small robot watering flowers in a lush green garden',
    tags: ['robot', 'garden', 'flowers', 'nature', 'cute'],
    style: '3D Render',
    subject: 'Robot gardener',
    mood: 'Calm',
    color_palette: ['#228B22', '#FF69B4'],
    use_case: 'Editorial',
    filename: 'robot-garden.webp',
    created_at: now(2),
  },
  {
    id: 'img-030',
    s3_key: 'mock/cat-library.webp',
    s3_url: TEST_URL(2),
    original_prompt: 'a cat sleeping in a library',
    enhanced_prompt: 'a cat curled up sleeping on old books in a grand library',
    tags: ['cat', 'library', 'books', 'cozy', 'indoor'],
    style: 'Oil Painting',
    subject: 'Cat in library',
    mood: 'Calm',
    color_palette: ['#8B4513', '#FFD700'],
    use_case: 'Editorial',
    filename: 'cat-library.webp',
    created_at: now(1),
  },
];

/** Total images available in mock mode. */
export const MOCK_TOTAL = MOCK_IMAGES.length;
